app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, RadioField, IntegerField, SelectField, BooleanField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo, Email, ValidationError
from app.models import UserInfo
from flask import session


# 登录表单
class LoginForm(FlaskForm):
    Email = StringField(label="邮箱", validators=[DataRequired('不能为空'), Email('邮箱不合法')])
    pwd = PasswordField(label="密码", validators=[DataRequired('不能为空')])
    remember_me = BooleanField(label="保持密码")
    submit = SubmitField(label="提交")


# 注册表单
class RegisterForm(FlaskForm):
    user = StringField(label="用户名", validators=[DataRequired(), Length(min=4, max=9, message="用户名的长度在4-9之间")])
    Email = StringField(label="邮箱", validators=[DataRequired('不能为空'), Email('邮箱不合法')])
    pwa1 = PasswordField(label="密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间")])
    pwa2 = PasswordField(label="新密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间"), EqualTo(fieldname='pwa1', message="两次密码不一致！")])
    sex = RadioField(label="性别", choices=[('1', '男'), ('2', '女')])
    age = IntegerField(label="年龄", validators=[DataRequired()])
    submit = SubmitField(label="提交")

    def validate_Email(self, field):
        # if UserInfo.query.filter_by(email= field.)
        pass


# 类别表单
class TypeForm(FlaskForm):
    typename = StringField(label="类别名称", validators=[DataRequired()])
    submit = SubmitField(label="提交")


# 修改密码表单
class PasswordChangeForm(FlaskForm):
    oldpassword = PasswordField(label="旧密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间") ])
    newpassword = PasswordField(label="新密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间")])
    password = PasswordField(label="确认密码", validators=[DataRequired(),Length(min=6, max=12, message="密码必须要在6-12之间"), EqualTo(fieldname='newpassword', message="两次密码不一致！") ])
    submit = SubmitField(label="提交")

    def validate_newpassword(self, field):
        User1 = UserInfo.query.filter_by(id=session['id']).first()
        if User1.verify_password(field.data):
            raise ValidationError('新密码不能和旧密码一致！！')


# 邮箱更新表单
class EmailChangeForm(FlaskForm):
    Email = StringField(label="邮箱", validators=[DataRequired('不能为空'), Email('邮箱不合法')])
    password = PasswordField(label="密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间") ])
    submit = SubmitField(label="提交")


# 重置密码表单
class ResetPasswordForm(FlaskForm):
    Email = StringField(label="邮箱", validators=[DataRequired('不能为空'), Email('邮箱不合法')])
    submit = SubmitField(label="提交")

    def validate_Email(self, field):
        User1 = UserInfo.query.filter_by(id=session['id']).first()
        if User1.Email != field.data:
            raise ValidationError('邮箱不存在！')


# 重置密码表单2
class ResetPassForm(FlaskForm):
    newpassword = PasswordField(label="新密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间")])
    password = PasswordField(label="确认密码", validators=[DataRequired(), Length(min=6, max=12, message="密码必须要在6-12之间"), EqualTo(fieldname='newpassword', message="两次密码不一致！")])
    submit = SubmitField(label="提交")

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session, redirect, url_for, request, jsonify, flash, current_app
from app.models import *
from app.main.forms import *
from . import main
from flask_login import login_user, logout_user, login_required, current_user
from app.email import send_email


@main.route('/')
def hello_world():
    # send_email('1573572431@qq.com', '默默', 'main/email/confirm', name="1234")
    return 'Hello World!'


# 登录页面
@main.route('/login/', methods=['GET', 'POST'])
def LoginView():
    form = LoginForm()
    if form.validate_on_submit():
        try:
            Email = form.Email.data
            pwa = form.pwd.data
            user1 = UserInfo.query.filter_by(Email=Email.lower()).first()
            if user1 is not None and user1.verify_password(pwa):
                session['id'] = user1.id
                # if user1.confirmed:
                login_user(user1, form.remember_me.data)
                next = request.args.get('next')
                if next is None or not next.startswith('/'):
                    next = url_for('main.index')
                return redirect(next)
                # else:
                #     flash("此账号未激活")
            else:
                flash('邮箱或者密码错误！！')
        except:
            db.session.rollback()
    return render_template('main/Login.html', form=form)


# 注册页面
@main.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            Email = form.Email.data
            user = form.user.data
            pwa = form.pwa1.data
            sex = form.sex.data
            if int(sex) == 1:
                u1 = UserInfo()
                u1.Email = Email
                u1.Username = user
                u1.password = pwa
                u1.Sex = '男'
            else:
                u1 = UserInfo()
                u1.Email = Email
                u1.Username = user
                u1.password = pwa
                u1.Sex = '女'
            db.session.add(u1)
            db.session.commit()
            token = u1.generate_confirmation_token()
            send_email(u1.Email, '激活账号', 'main/email/confirm', user=u1, token=token)
            flash("有一件确认邮件已经发送到您的邮箱,请及时激活账号！！")
            return redirect(url_for('main.LoginView'))
        except:
            db.session.rollback()
    return render_template('main/registered.html', form=form)


# 注销页面
@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已成功注销')
    return redirect(url_for("main.index"))


# 修改密码
@main.route('/passupdate/', methods=['GET', 'POST'])
def PasswordChangeView():
    form = PasswordChangeForm()
    newpass = form.newpassword.data
    oldpass = form.oldpassword.data
    if form.validate_on_submit():
        try:
            t1 = UserInfo.query.filter_by(id=session['id']).first()
            if t1.verify_password(oldpass):
                t1.password = newpass
                db.session.add(t1)
                db.session.commit()
                return redirect(url_for('main.login'))
        except:
            raise RuntimeError('修改错误！！')
    return render_template('main/ChangePass.html', form= form)


# 更新邮箱
@main.route('/EmailChange/', methods=['GET', 'POST'])
def EmailChangeView():
    form = EmailChangeForm()
    email = form.Email.data
    pwd = form.password.data
    t1 = UserInfo.query.filter_by(id=session['id']).first()
    if form.validate_on_submit():
        try:
            if t1.verify_password(pwd) and t1.Email != email:
                t1.Email = email
                db.session.add(t1)
                db.session.commit()
                token = t1.generate_confirmation_token()
                send_email(t1.Email, '重置邮箱', 'main/email/confirm', user=t1, token=token)
                flash("有一件确认邮件已经发送到您的邮箱,请重置邮箱")
        except:
            raise RuntimeError("密码或者邮箱不正确")
    return render_template('main/EmailChange.html', form= form)


# 重置密码
@main.route('/ResetPassword/', methods=['GET', 'POST'])
def ResetPasswordView():
    form = ResetPasswordForm()
    email = form.Email.data
    if form.validate_on_submit():
        t1 = UserInfo.query.filter_by(Email=email).first()
        if t1.Email == email:
            token = t1.generate_confirmation_token()
            send_email(t1.Email, '重置密码密码', 'main/email/ResetPassword', user=t1, token=token)
            flash("有一件确认邮件已经发送到您的邮箱,")
        else:
            flash("邮箱不正确!")
    return render_template('main/ResetPassword/ResetEmail.html', form=form)


# 重置密码确认视图
@main.route('/ResetPasswordComfirm/', methods=['GET', 'POST'])
def ResetPasswordComfirmView():
    form = ResetPassForm()
    pwd = form.newpassword.data
    if form.validate_on_submit():
        t1 = UserInfo.query.filter_by(id=session['id']).first()
        try:
            t1.password = pwd
            db.session.add(t1)
            db.session.commit()
            flash("密码重置成功！！")
            return redirect(url_for('main.index'))
        except:
            raise RuntimeError('重置失败')
    return render_template('main/ResetPassword/ResetPass.html', form= form)


# 邮箱修改
@main.route('/updatepass/<token>')
@login_required
def ResetPassword(token):
    if current_user.confirm(token):
        db.session.commit()
        flash("填写新的密码！！")
    else:
        flash("重置失效！！")
    return redirect(url_for("main.ResetPasswordComfirmView"))


# 激活账户的视图函数
@main.route('/confirm/<token>')
@login_required
def confirm(token):
    if current_user.confirmed:
        return redirect(url_for('main.index'))
    if current_user.confirm(token):
        db.session.commit()
        flash("您已经激活您的账号！")
    else:
        flash("激活链接无效或已过期")
    return redirect(url_for("main.index"))

app/templates/main/ChangePass.html
{% extends 'base.html' %}


{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}
    <div class="col-md-4 col-md-offset-4">
    <h2>用户修改密码</h2>
     {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

app/templates/main/EmailChange.html
{% extends 'base.html' %}


{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}
    <div class="col-md-4 col-md-offset-4">
    <h2>用户修改邮箱</h2>
     {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

app/templates/main/Login.html
{% extends 'base.html' %}

{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}
    <div class="col-md-4 col-md-offset-4">
    <h2>用户登录</h2>
     {{ wtf.quick_form(form) }}
    <a href="{{ url_for('main.register') }}">点击注册</a>
    </div>

{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}


{%  block content %}
    <div>
        按照电话溥的类型：
        <select id="selectid">
            <option value="-1">全部</option>
            {% for i in typetest %}
                <option value="{{ i.id }}">{{ i.name }}</option>
            {% endfor %}
        </select>
        姓名
        <input placeholder="模糊姓名。。"  id="getname">
        <button type="button" class="btn btn-danger" id="btuclick">搜索</button>
    </div>

    <button type="button" class="btn btn-success"><a href="{{ url_for('main.telbook') }}">新增联系人</a></button>
    <button type="button" class="btn btn-info"><a href="{{ url_for('main.TypeView') }}">新增类别</a></button>
    <table class="table table-striped">
    <thead>
        <tr>
            <td>姓名</td>
            <td>电话</td>
            <td>类型</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody id="tables">
        {% for i in tel_book %}
            <tr>
                <td>{{ i.name }}</td>
                <td>{{ i.Tel }}</td>
                <td>{{ i.getname() }}</td>
                <td><button type="button" class="btn btn-danger"><a href="/delete/{{ i.id }}/">删除</a></button><button type="button" class="btn btn-primary"><a href="/telbook/?id={{ i.id }}">修改</a></button></td>
            </tr>
        {% endfor %}
    </tbody>
    </table>
{% endblock %}

app/templates/main/registered.html
{% extends 'base.html' %}

{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}
     <div class="col-md-4 col-md-offset-4">
        <h2>用户注册</h2>

        {{ wtf.quick_form(form) }}
     </div>
{%  endblock %}

app/templates/main/telbookadd.html
{% extends 'base.html' %}

{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}

    {{ wtf.quick_form(form) }}

{% endblock %}

app/templates/main/typepage.html
{% extends 'base.html' %}

{%  import 'bootstrap/wtf.html' as wtf %}

{%  block content %}

    {{ wtf.quick_form(form) }}

{% endblock %}